Create a NumPy ndarray Object

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Use a tuple to create a NumPy array

In [15]:
import numpy as np
arr = np.array((1, 2, 4, 6, 8, 9))
print(arr)
print(type(arr))

[1 2 4 6 8 9]
<class 'numpy.ndarray'>


Dimensions in Arrays----->A dimension in arrays is one level of array depth (nested arrays).

0D Array

In [16]:
import numpy as np
arr = np.array(100)
print(arr)

100


1D Array

In [17]:
import numpy as np
arr = np.array((1, 3, 5, 7, 9, 11, 13))
print(arr)

[ 1  3  5  7  9 11 13]


2D Array

In [18]:
import numpy as np
arr = np.array([[1, 2, 3], [2, 4, 6]])
print(arr)

[[1 2 3]
 [2 4 6]]


3D Array

In [19]:
import numpy as np
arr = np.array([[[1,3,5], [7, 9, 11]], [[2, 4, 6], [8, 10, 12]]])
print(arr)

[[[ 1  3  5]
  [ 7  9 11]]

 [[ 2  4  6]
  [ 8 10 12]]]


Check Number of Dimensions

In [20]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Higher Dimensional Arrays

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("Number of dimensions:", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions: 5
